# {time_n} Выводит 1 минута. {time2_n} Выводит 1 минуту. {time3_n} Выводит чч:мм:сс. Работает не во всех сообщениях!
# {time_start}, {time2_start}, {time3_start} Время до начала ивента
# {time_locked}, {time2_locked}, {time3_locked} Время до открытия аирдропа
# {time_end}, {time2_end}, {time3_end} Время до окончания аирдропа
# {x}, {y}, {z} координаты аирдропа
# {name} имя аирдропа
# {world} мир в котором появится аирдроп
chests:
  default:
    chest-id: default
    chest-name: '&7Обычный сундук'
    chest-inventory-size: 54
    item-chance-boost: 0 #не работает
    chest-spawn-world: world
    chest-spawn-radius-min: -2000
    chest-spawn-radius-max: 2000
    chest-radius-protect: 15
    time-start-interval: 2 #Сколько до начала в минутах
    duration-event: 1 #сколько будет закрыт сундук
    time-stop-event: 1 #через сколько после начала пропадёт аирдроп
    chest-material-locked: RESPAWN_ANCHOR
    chest-material-unlocked: CHEST
    helix: 'DOUBLE-HELIX' #Варианты HELIX, DOUBLE-HELIX, NONE # Настройки спиралей ниже
    random-particle: true # true / false ниже настройка эффекта

# {px} заменяется на prefix. Во всех сообщениях
config-version: 1
settings:
  world-guard-flags: #не работает
    PVP: ALLOW
    USE: ALLOW
    CHEST_ACCESS: ALLOW
    CREEPER_EXPLOSION: DENY
    TNT: DENY
    FIRE_SPREAD: DENY
    LAVA_FIRE: DENY
    OTHER_EXPLOSION: DENY
  #настройки спавна аирдропа
  min-online-players: 1 #минимальное количество игроков на сервере для старта ивента
  #настройки таймингов появления аирдропа
  time-start-interval: 2 #Сколько до начала в минутах
  duration-event: 1 #сколько будет закрыт сундук
  time-stop-event: 1 #через сколько после начала пропадёт аирдроп
  #прочее
  empty-slot-chance: 25 #Шанс того что слот будет пустым от 0 до 100. 0 - отключит, а 100 сделает сундуки всегда пустыми
  laser-settings: #Настройки лазера
    laser: 'CRYSTAL_LASER' # варианты: CRYSTAL_LASER, GUARDIAN_LASER, NONE
    laser-view-distance: 50 # в блоках
    laser-time: 300 # в секундах
  effect-settings: #Настройки эфектов
    explosion-power: 4.75 #Сила взрыва для Эфекта Explosion. 4.75 = взрыву заряженного крипера
    drop-open-effect: # Что будет происходить когда аир дроп откроется варианты - strikeLightning (молния), fireWork (фейерверк), explosion (взрыв, блоки не взорвутся), fakeStrikeLightning (будет эффект удара молнии без нанесения урона)
      - explosion
      - strikeLightning
      - fireWork
      - fakeStrikeLightning
      - defenders
    #Настройки Спиралей
    helix-settings:
      close: #цвет когда аирдроп закрыт
        color:
          r: 255
          g: 0
          b: 0
      open: #цвет когда аирдроп открыт
        color:
          r: 0
          g: 255
          b: 0
      radius: 1 # радиус спирали
      view-distance: 50 # дистанция с которой будет видно спираль
      height-y: 50 # насколько высоко протянется спираль над аирдропом
      helix-pitch: 0.05 # Расстояние между партиклами. Не рекомендуется делать меньше
      offset-y: 3 # смещение по высоте относительно аирдропа
      offset-x: 0.5 # смещение по x
      offset-z: 0.5 # смещение по z
    # Двойная спираль
    double-helix-settings:
      close:
        color:
          r: 255
          g: 0
          b: 0
        color2:
          r: 0
          g: 137
          b: 255
      open:
        color:
          r: 0
          g: 255
          b: 0
        color2:
          r: 255
          g: 255
          b: 0
      radius: 1 # радиус спирали
      view-distance: 50 # дистанция с которой будет видно спираль
      height-y: 50 # насколько высоко протянется спираль над аирдропом
      helix-pitch: 0.05 # расстояние между партиклами. Не рекомендуется делать меньше
      offset-y: 3 # смещение по высоте относительно аирдропа
      offset-x: 0.5 # смещение по x
      offset-z: 0.5 # смещение по z
    #Рандомные частицы
    random-particle:
      particle: "TOTEM" #партиклы
      particle2: "FLAME"
      amount: 50 #количество партиклов умножается на 2 так как одновременно появится particle и particle2
      radius: 5 #радиус спавна партиклов
      view-distance: 50 # дистанция с которой будет видно партиклы

  defenders: #мобы охранники
    name: "&c&lХранитель"
    type: VINDICATOR # все мобы - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html список под текстом 'All Known Subinterfaces:'
msg:
  item-del: '&c&lПКМ &f- удалить предмет из списка'
  unknown-command: '&cНеизвестная команда'
  invalid-key: '&cПредметов с таким ключом нет!'
  only-players: 'Only players!'
  reload: '&aКонфиг перезагружен!'
  item-add: '&aПредметы добавлены по ключу {key}'
  error-number: '&cОшибка возможно вы ввели не число! детали в консоли'
  prefix: '&7[&6АирДроп&7]' #Заменяет {px}
  drop-locked: '&cЗакрыто. Откроется через {time3_locked}' #Вторая строчка над сундуком
  drop-unlocked: '&aОткрыто' # Вторая строчка над сундуком
  chest-locked: '{px} &cСундук закрыт!' # Выводится когда, игрок пытается открыть сундук
  no-prem: '&cУ Вас нет разрешения!' # Выводится когда у игрока нет разрешения
  no-event: '{px} &cИзвините но ивент не начат!'
  few-arguments: '{px} &cМало аргументов!'
  drop-spawning: '{px} {name} &7только что &6появился &fна координатах &6{x}, {y}, {z}' # Выводится когда ивент начался
  event-end: '{px} {name} &7окончен!' # Выводится когда закончился
  msg-open-event: '{px} {name} &aоткроется &fчерез &6{time2_locked}!' # notification-open-time
  msg-start-event: '{px} {name} &aпоявится &fчерез &6{time2_start}!' # notification-time
  papi-event-is-activity: '&aНачат!'
  papi-chest-is-unlocked: '&aУже открыт!'
  papi-poz: '{x}, {y}, {z}'
  papi-poz-none: '&cНет активного ивента!' #Используют %airdrop_poz%, %airdrop_locked% и %airdrop_locked2%
  notification-open-time: [60, 30, 10, 5, 3, 2, 1] #за сколько до открытия сундука выводить сообщение о его предстоящем открытии в секундах
  notification-time: [60, 30, 10, 5, 3, 2, 1] #за сколько до начала ивента выводить сообщение о его предстоящем начале в секундах
  format-time: # Формат вывода времени
    - ' час '
    - ' часа '
    - ' часов '
    - ' минута '
    - ' минуты '
    - ' минут '
    - ' секунда'
    - ' секунды'
    - ' секунд'
    - ' час '
    - ' минуту '
    - ' секунду'

black-List:
  - LAVA
  - WATER
  - SNOW
  - BEDROCK
  - CACTUS
  - FIRE
  - END_PORTAL
  - END_CRYSTAL
  - END_PORTAL_FRAME
  - NETHER_PORTAL
  - ACACIA_LEAVES
  - AZALEA_LEAVES
  - BIRCH_LEAVES
  - OAK_LEAVES
  - DARK_OAK_LEAVES
  - SPRUCE_LEAVES
  - FLOWERING_AZALEA_LEAVES
  - JUNGLE_LEAVES

data: # тут хранятся предметы