# Translation by google translate
# {time} Displays 1 minute. {time2} Displays 1 minute. Does not work in all messages!
# {px} is replaced with prefix. In all messages
settings:
  #airdrop spawn settings
  spawn-max: 2000 #Maximum
  spawn-min: -2000 #Minimum coordinate
  world: world #the world in which the airdrop will appear
  radius-protect-block: 15 #airdrop protection size
  #airdrop spawn timing settings
  time-start-interval: 2 #How many minutes before the start
  duration-event: 1 #how long will the chest be closed
  time-stop-event: 1 #how long after the start will the airdrop disappear

  empty-slot-chance: 25 #chance that the slot will be empty from 0 to 100. 0 will disable, and 100 will make the chests always empty
  laser-settings: #Laser settings
    laser: 'CRYSTAL_LASER' #options: CRYSTAL_LASER, GUARDIAN_LASER, NONE
    laser-view-distance: 50 # in blocks
    laser-time: 300 # in seconds
  effect-settings: #Effect settings
    explosion-power: 4.75 #The force of the explosion for the Explosion Effect. 4.75 = charged creeper explosion
    drop-open-effect: #What will be reasonable when airdrops are valid options - strikeLightning (lightning), fireWork (fireworks), Explosion (explosion, blocks will not explode), fakeStrikeLightning (there will be a lightning strike effect without damaging damage)
      - explosion
      - strikeLightning
      - fireWork
      - fakeStrikeLightning
msg:
  item-del: '&c&lRIGHT CLICK &f- remove an item from the list'
  unknown-command: '&cUnknown command'
  invalid-key: '&cThere are no items with this key!'
  only-players: 'Only players!'
  reload: '&aConfig reloaded!'
  item-add: '&aItems added by key {key}'
  error-number: '&cError, you may not have entered a number! details in console'
  prefix: '&7[&6AirDrop&7]' #Replaces {px}
  drop-name-holo: '&aAir drop' # The first line of the hologram above the chest
  drop-locked: '&cClosed. Opens in {time2}' #Second line above the chest
  drop-unlocked: '&aOpen' #Second line above the chest
  chest-locked: '{px} &cChest closed!' # Printed when a player tries to open a chest
  no-prem: '&cYou do not have permission!' # Displayed when the player does not have permission
  no-event: '{px} &cSorry, but the event has not started!'
  few-arguments: '{px} &cFew arguments!'
  drop-spawning: '{px} &fAirdrop just appeared on coordinates &6{x}, {y}, {z}' # Displayed when the event has started
  event-end: '{px} &fAirdrop is over!' # Dispatched when finished
  msg-open-event: '{px} &fAirdrop &awill open &fчерез &6{time2}!' # notification-open-time
  msg-start-event: '{px} &fAirdrop &awill appear &fчерез &6{time2}!' # notification-time
  notification-open-time: #how long before the opening of the chest, display a message about its upcoming opening in seconds
    - 60
    - 30
    - 10
    - 5
    - 3
    - 2
    - 1
  notification-time: #how long before the start of the event to display a message about its upcoming start in seconds
    - 60
    - 30
    - 10
    - 5
    - 3
    - 2
    - 1
  format-time: # Time output format
    - '1 hour'
    - 'hour'
    - 'h.'
    - '1 minute'
    - 'minute'
    - 'min.'
    - '1 second'
    - 'second'
    - 'sec.'
    - 'h.'
    - '1 minute'
    - 'minutes'
    - '1 second'
    - 'second'
black-List:
  - LAVA
  - WATER
  - SNOW
  - BEDROCK
  - CACTUS
  - FIRE
  - END_PORTAL
  - END_CRYSTAL
  - END_PORTAL_FRAME
  - NETHER_PORTAL
  - ACACIA_LEAVES
  - AZALEA_LEAVES
  - BIRCH_LEAVES
  - OAK_LEAVES
  - DARK_OAK_LEAVES
  - SPRUCE_LEAVES
  - FLOWERING_AZALEA_LEAVES
  - JUNGLE_LEAVES

data: # items are stored here
